[Icon Theme]
Name=Innometrics
Comment=Innometrics
Inherits=breeze
Directories=apps/16,apps/32,apps/64,apps/128,apps/256,apps/512,apps/1024,apps/scalable

########## Applications

[apps/16]
Context=Applications
Type=Fixed
Size=16

[apps/32]
Context=Applications
Type=Fixed
Size=32

[apps/64]
Context=Applications
Type=Fixed
Size=64

[apps/128]
Context=Applications
Type=Fixed
Size=128

[apps/256]
Context=Applications
Type=Fixed
Size=256

[apps/512]
Context=Applications
Type=Fixed
Size=512

[apps/1024]
Context=Applications
Type=Fixed
Size=1024

[apps/scalable]
Context=Applications
Type=Scalable
Size=22
MinSize=1
MaxSize=256

########## EOF
