#!/usr/bin/env bash
echo 'Using $AMO_JWT_ISSUER and $AMO_JWT_SECRET'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

yarn build
cd "$DIR/distribution"

npx web-ext build --overwrite-dest
npx web-ext sign --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET

echo 'Usnig private key generated by `yarn crx keygen`'
npx crx pack -p key.pem -o innometrics.crx '.'

mv web-ext-artifacts/*.xpi innometrics.xpi -f
